spring.application.name=tracking-service

# Server port
server.port=8082

# Supabase Database connection
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.etbwuojtawcvzsbqgxkp
spring.datasource.password=gHAk9!BxF!z7a.,
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=tracking_schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT configuration (must match Auth Service)
jwt.secret=shuttletrack-super-secret-key-2024-must-be-long-enough
jwt.expiration=86400000

# Auth Service URL
auth.service.url=http://172.20.10.11:8081