spring.application.name=auth-service
server.port=8081
# ===== Supabase Postgres connection =====
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.etbwuojtawcvzsbqgxkp
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}
jwt.expiration.ms=2592000000