spring.datasource.url=jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.lvqqjlaaabbzfnyugpwd
spring.datasource.password=mV0vh2Y2RbDbxshd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080